on: 
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  run:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - uses: Geode-solutions/actions/get-release@master
      id: repos
      with:
        repository: ${{ inputs.repos }}
        file: '-win64-private.zip'
        token: ${{ secrets.TOKEN }}
    - name: Generate package
      run: |
        choco install openssl -r --no-progress
        if(!(test-path build)) { mkdir build }
        cd build
        $version = ${env:GITHUB_REF} -replace 'refs\/tags\/v', ''
        echo "::set-output name=version::$version"
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH:PATH="${{ steps.repos.outputs.path }}" -D${{ inputs.name }}_WITH_TESTS:BOOL=OFF -DINCLUDE_PYBIND11:BOOL=ON -DCPACK_PACKAGE_VERSION:STRING=$version -DCPACK_SYSTEM_NAME:STRING=win64 ..
        cmake --build . --config Release -j 2
        cpack -D CPACK_COMPONENTS_ALL="public;private" -C Release .
        get-childitem *.zip | foreach { rename-item $_ $_.Name.Replace(".zip", "-private.zip") }
        cmake --build . --target PACKAGE --config Release
    - name: Upload
      uses: geode-solutions/action-gh-release@master
      with:
        files: build/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
